### ISSUE TITLE
how to deal with ncch?

### ISSUE THREAD

**Issue by Lo1nt** [shijimasoft/cia-unix#1]
Im not sure am i right.

I do with .cia file with decrypt.py and get output file .ncch.

While actually my citra reads cia file? How may I get cia file, from ncch?

Does the next step do with ctrtool or makerom? I try search online but didnt get useful guide.

**Comment by shijimasoft** [comment]
`.ncch` files are the "unpacked" partitions of `.cia` games (or dlc/patch), and are not meant to be used by the user.
cia-unix will unpack and decrypt partitions automatically, and will save a `.cci` file, named with the original game name (`.cia` for dlc/patch) and a "decrypted" suffix. all `.ncch` will be removed after decryption.

#### Code reference
```crystal
# cleanup
Dir["*-decfirst.cia"].each do |fname| File.delete(fname) end
Dir["*.ncch"].each do |fname| File.delete(fname) end
```
