### ISSUE TITLE
'cia-unix.cr' does not exist

### ISSUE THREAD

**Issue by Kempred** [shijimasoft/cia-unix#10]
Hi !

When I try to build from source with the "crystal build cia-unix.cr --release --no-debug" command, I get an error saying "'cia-unix.cr' does not exist".
Did I miss something ?

Thanks,
Bye

**Comment by shijimasoft** [comment]
Hello! Make sure you are in the right directory when you invoke the `crystal` command, otherwise the compiler will not find the source code.

To do this from the terminal simply run: `cd cia-unix/`

**Comment by shijimasoft** [comment]
Did you solved the issue?

**Comment by ildiem** [comment]
Hello! I'm having the same issue as OP, even though I'm using the `crystal` command in the correct directory. Full error message reads: `Error: Error opening file with mode 'r': '/Users/ildiem/Downloads/cia-unix/cia-unix.cr': No such file or directory`.

this is everything in the file `cia-unix`. Am I missing anything?
<img width="274" alt="Image" src="https://github.com/user-attachments/assets/c80f7945-b956-4aae-9b74-37e3efe8e06f" />

**Comment by ildiem** [comment]
Never mind! I totally missed the `cia-unix.cr` file in the repo. Was able to use the tool successfully; thanks so much!
