### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by Idkwhyiamherebutokay** [shijimasoft/cia-unix#11]
Some tools are missing, do you want to download them? (y/n): y
--: ./dltools.sh: Permission denied
ctrtool not found. Make sure it's located in the same directory

Haven't used Crystal before, so I might be doing something wrong, but shouldn't the tools be automatically downloaded?

**Comment by shijimasoft** [comment]
Please check that `dltools.sh` have execute permission, if not just run from terminal `chmod +x dltools.sh` (in the same cia-unix directory)

**Comment by Idkwhyiamherebutokay** [comment]
Thank you for helping out. Now here is what I get:
Some tools are missing, do you want to download them? (y/n): y
 * Downloading ctrtool
./dltools.sh: line 27: wget: command not found
 * Extracting ctrtool
unzip:  cannot find or open ctrtool-v1.2.0-macos_x86_64.zip, ctrtool-v1.2.0-macos_x86_64.zip.zip or ctrtool-v1.2.0-macos_x86_64.zip.ZIP.
mv: rename ctrtool-v1.2.0-macos_x86_64/ctrtool to ./ctrtool: No such file or directory
 * Downloading makerom
./dltools.sh: line 32: wget: command not found
 * Extracting makerom
unzip:  cannot find or open makerom-v0.18.3-macos_x86_64.zip, makerom-v0.18.3-macos_x86_64.zip.zip or makerom-v0.18.3-macos_x86_64.zip.ZIP.
mv: rename makerom-v0.18.3-macos_x86_64/makerom to ./makerom: No such file or directory
 * Downloading decrypt.py
./dltools.sh: line 54: wget: command not found
 * Cleaning up
chmod: ctrtool: No such file or directory
chmod: makerom: No such file or directory

ctrtool not found. Make sure it's located in the same directory


Im def doing something wrong here, but I am not sure what. Sorry for the bother!

**Comment by Idkwhyiamherebutokay** [comment]
Nevermind! got it to work. Had to first remove the permissions and then re-add them for some reason. Thanks for the help!

**Comment by shijimasoft** [comment]
Okk nice! 😊
