### ISSUE TITLE
ctrtool not found

### ISSUE THREAD

**Issue by Dudegamer456** [shijimasoft/cia-unix#12]
im on linux and after being like 2 hours trying to search everything i needed to make this work i tried to run the program on crystal but then it says "ctrtool not found" even though it is right there, in the same file, and ive checked that it is the latest version (1.2.0) but it just wont find it. and ive checked many times to see if there are any differences on the names but its just the same exact file and it cant find it :(
and when it asks me if i want to download the missing tools it says **--: 1: ./dltools.sh: not found** even though it is RIGHT THERE TOO :,D
if you can give me any tips i would really appreaciate it, thank you.

**Comment by shijimasoft** [comment]
Please check if _dltools.sh_ have `+x` (execute permission). Doing `chmod +x dltools.sh` will solve the problem :)

**Comment by shijimasoft** [comment]
Same thing with _ctrtool_ and _makerom_: `chmod +x ctrtool makerom`

**Comment by Dudegamer456** [comment]
oh thank you so much!! and i didnt expect you to reply so fast :D 
i did what you told me but it still cant find them :( 
though i found a way to run dltools.sh on the files , just that it will be the same and the program just wont find it 
but i really appreciate that you replied and if you can still tell me what can i do i would really really appreciate it

**Comment by shijimasoft** [comment]
Ok let's solve it step by step:
1. Download cia-unix and dltools in the same folder (please rename `cia-unix_0.1.2b_linux-x86_64.zip` to `cia-unix`)
2. Go to that folder inside the terminal and type `ls` (please upload a screenshot of the terminal if you can)
3. Check if all files have execute permission (if not, do the procedure above)
4. Execute cia-unix or dltools.sh with `./cia-unix` or `./dltools.sh`

**Comment by shijimasoft** [comment]
Did you solved the issue?

**Comment by adammenges** [comment]
on macOS folks, `brew install wget`
