### ISSUE TITLE
[SETTING ERROR] Argument "-rsf" is required

### ISSUE THREAD

**Issue by AriaOfWater** [shijimasoft/cia-unix#13]
When executing the program (after tinkering with missing libpcre.so files, and having to put decrypt.py in a PATH folder), it returns the following output:
```bash
Decrypting: Stella Glow (EUR).cia...
CIA Type: Game
[SETTING ERROR] Argument "-rsf" is required
Removing cache...
Log saved
```
Then quits to prompt. It happens independently of ./cia-unix being invoked with the argument "-rsf" (happens with *and* without)
I do not have access to my real, physical 3DS for a bit, so was hoping to make this work somehow

**Comment by shijimasoft** [comment]
Hello! This error is coming from makerom, specifically it requires a ROM Spec File (*.rsf), which rom are you trying to decrypt?

**Comment by M-K-S-P** [comment]
Same problem. Pokemon Omega Ruby taken from hshop.

**Comment by shijimasoft** [comment]
Please try to add `-desc` parameter when last makerom command is invoked (before `-ciatocci`)

https://github.com/shijimasoft/cia-unix/blob/f2a7dfc41d8bc7825481e3e1056cfded017b681b/cia-unix.cr#L157

**Comment by shijimasoft** [comment]
Could you try the latest commit? (58f9f95), I was able to reproduce and fix the error :)

**Comment by shijimasoft** [comment]
@M-K-S-P @AriaOfWater Can I consider the issue closed?
