### ISSUE TITLE
How to run the package for someone who does not know how to use Python

### ISSUE THREAD

**Issue by Fran355D** [shijimasoft/cia-unix#14]
Hi there, firstly, thank you for the effort you put on doing this, I know that for someone who has some knowledge in coding this can be a piece of cake. Unfortunately that is not my case haha. So, I wonder if you could help me with running this. I will be attaching some screens of how I see cia-unix-experimental in my PY3 folder.

Thank you

<img width="961" alt="Captura de pantalla 2024-02-07 a las 10 41 07" src="https://github.com/shijimasoft/cia-unix/assets/102892785/f71c4b85-0d23-4143-8521-f3f327663893">

**Comment by shijimasoft** [comment]
Please refer to my answer of this issue: https://github.com/shijimasoft/cia-unix/issues/18
