### ISSUE TITLE
Issue extracting ctrtool, had to download zip manually

### ISSUE THREAD

**Issue by mroemore** [shijimasoft/cia-unix#16]
This happened on WSL Ubuntu. Here is the ``uname -a`` output: ``5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux``. running ``dltools.sh`` gave the following error:

![Screenshot 2024-03-11 101540](https://github.com/shijimasoft/cia-unix/assets/6340452/a9f019ff-e62b-43e9-b59d-8e95a84c8c4e)

I was able to fix the issue by downloading the zip file myself using wget: ``wget https://github.com/3DSGuy/Project_CTR/releases/download/ctrtool-v1.2.0/ctrtool-v1.2.0-ubuntu_x86_64.zip``, then re-running the shell script. Having looked at the shell script, my wget command looked identical to the one in the script, so I'm not really sure why this happened.

**Comment by mroemore** [comment]
For what it's worth, the python3 version of the script was able to download and extract no problem.

**Comment by shijimasoft** [comment]
It is strange, `dltools.sh` looks for “linux-gnu” string, reference: https://github.com/shijimasoft/cia-unix/blob/12814d1ca49bf8513e58d6520888d6d23c261e4f/dltools.sh#L39

Is any string shown before that? (the content that follows _linux-gnu_ is indifferent instead)

**Comment by mroemore** [comment]
No string before that, but I don't think it's an issue with system detection per se, because unzip seems to think the file has downloaded.

I'm wondering if I just got unlucky, I have a bad internet connection so maybe the zip got corrupted while downloading.

**Comment by shijimasoft** [comment]
I need to investigate more, I was not able to reproduce the issue.
Please try to update all linux packages with `sudo apt upgrade` and `sudo apt update`

**Comment by shijimasoft** [comment]
I was able to reproduce the first problem (inherent to the mv command) installing the correct WSL version and I just tried to fix the dependencies script, please let me know if it works now. Thank you :)

**Comment by shijimasoft** [comment]
I'm considering the issue closed, please if the problem persist reopen the issue and tag me. Thank you :)
