### ISSUE TITLE
dependancy hell on Linux

### ISSUE THREAD

**Issue by ItsRogueRen** [shijimasoft/cia-unix#17]
Running Fedora linux and I keep running into dependency issues. At first it was with pycrypto, but the alternative pycryptodome fixed that. Hoever now I get "error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory" when trying to run it

**Comment by shijimasoft** [comment]
Unfortunately, the problem of dependencies is very common, especially when there are python libraries that rely on C bindings on different linux distributions.
I was working on a project to make cia-unix dependency free, translating the [decryption module in rust](https://github.com/shijimasoft/ctrdecrypt).
Right now my advice is to use the python3 version and compile cia-unix with the crystal compiler

**Comment by shijimasoft** [comment]
Hello, @ItsRogueRen could you try the newer cia-unix version?

**Comment by ItsRogueRen** [comment]
> Hello, @ItsRogueRen could you try the newer cia-unix version?

New version runs to make the cci file but no further, unless I'm just missing something

**Comment by shijimasoft** [comment]
Yes! `.cci` files are decrypted roms
