### ISSUE TITLE
[NCCH ERROR]

### ISSUE THREAD

**Issue by ExoPlant** [shijimasoft/cia-unix#2]
`[NCCH ERROR] CXI's ID cannot be modified without the ability to resign the AccessDesc`
I am attempting to decrypt Mario Kart 7 from many different sources (none work)

**Comment by ExoPlant** [comment]
It seems my cia-unix is borked

**Comment by shijimasoft** [comment]
Note: decrypt.py is not able to decrypt all types of cia.

Try compiling latest cia-unix source to be sure it doesn’t depend on that.

**Comment by alilahriaz** [comment]
Just flagging that I hit this too

```
[NCCH ERROR] CXI's ID cannot be modified without the ability to resign the AccessDesc
[RESULT] Failed to build CCI (ret = -3)
Decryption failed
```

My env is
```
Crystal 1.5.0 [994c70b10] (2022-07-06)
Python 2.7.16 (default, Aug 30 2021, 14:43:11) 
```

This is using `master` branch, can try v0.1.1 too

**Comment by shijimasoft** [comment]
That *NCCH ERROR* is caused by a non-implemented makerom feature

**Code reference**
```c
if(/*keys->rsa.requiresPresignedDesc && */!IsCfa(hdr)){
	fprintf(stderr,"[NCCH ERROR] CXI's ID cannot be modified without the ability to resign the AccessDesc\n"); // Not yet yet, requires AccessDesc Privk, may implement anyway later
	return -1;
}
```

https://github.com/3DSGuy/Project_CTR/blob/319c4c6a24747a6def3c012312ed13a2f76bb369/makerom/ncch.c#L939-L942
