### ISSUE TITLE
"[SETTING ERROR] Argument "-rsf" is required" --> with .3ds file

### ISSUE THREAD

**Issue by Vat1n** [shijimasoft/cia-unix#21]
Hello,
[Mac 10.14]
I'm having some troubles launching the decryption with the Terminal Mac for an Ocarina of Time rom which has the **.3ds extension** (and not .cia) in order to use it in Citra. 

### What I've done before :
I installed the cia-unix-main.zip (and unzipped it)
I installed the 0.32.0 version of Crystal (the most newest versions are incompatible with my mac, so I decided to take an earlier version)
I executed the dltools.sh in order to get the differents dependencies
I compiled with crystal build cia-unix.cr --release --no-debug
I've carefully put the rom into the _cia_unix_main_ folder.

### Here is the output from the terminal :
```
popos-Mac-Pro-2:cia-unix-main popo$ ./cia-unix /Users/popo/Desktop/EMULATION/CITRA/cia-unix-main/3DS1259\ -\ Legend\ of\ Zelda\ -\ Ocarina\ of\ Time\ 3D\,\ The\ \(USA\)\ \(En\,Fr\,Es\)\ \(Rev\ 1\).3ds 
Decrypting: 3DS1259 - Legend of Zelda - Ocarina of Time 3D, The (USA) (En,Fr,Es) (Rev 1).3ds...
dyld: cannot load 'ctrdecrypt' (load command 0x80000034 is unknown)
Building decrypted 3DS1259 - Legend of Zelda - Ocarina of Time 3D, The (USA) (En,Fr,Es) (Rev 1) 3DS...
[SETTING ERROR] Argument "-rsf" is required
Decryption failed

Removing cache...
Log saved
```

I know that someone already did a post on the "-rsf" argument. However, according to the solution, I modified the line (in the cia-unix.cr file)
`log.puts %x[./makerom -ciatocci '#{decfirst}' -o '#{cutn}-decrypted.cci']`
to `log.puts %x[./makerom -desc -ciatocci '#{decfirst}' -o '#{cutn}-decrypted.cci']` (added -desc)
And it didn't solve the problem.

### Four hypothesis :
- I may have misunderstood the solution
- The solution is available only for .cia files.
- The Crystal I have isn't new enough (in the case there is new features in the decrypter code)
- I don't have the correct version of the decrypter (should I check in the "release" tab of the github page ?)

**Comment by shijimasoft** [comment]
The problem probably involves the ctrdecrypt dependency:
I am not sure if universal binaries (x86_64/arm64) works with macOS versions lower than 11. In that case, after downloading all dependencies, you might try compiling the ctrdecrypt dependencies for your macOS architecture (x86_64) and replace the universal binary with the one you compiled with your device (x86_64).

**Comment by shijimasoft** [comment]
In addition, regarding cia-unix, you can find automatically compiled binaries from github in the [actions section](https://github.com/shijimasoft/cia-unix/actions) or in the most recent [releases](https://github.com/shijimasoft/cia-unix/releases) so you do not have to download the crystal compiler. Your machine is definitely: `macos-x86_64`

**Comment by Vat1n** [comment]
I did the replacement of the old "ctrdecrypt" file with the new compiled, and it worked ! Thanks a lot !

**Comment by shijimasoft** [comment]
No problem :)
