### ISSUE TITLE
[SETTING ERROR] Argument "-rsf" is required

### ISSUE THREAD

**Issue by 9tin9tin9** [shijimasoft/cia-unix#3]
When I tried to run inside a directory containing a cia file, I got this error message
`[SETTING ERROR] Argument "-rsf" is required`
log:
```
2022-08-01 15:40:36 UTC

Partitions extracted
```
btw I patched cia-unix.cr to use python3 instead of python2.7
does that matter?

**Comment by shijimasoft** [comment]
I tried with newer version of python3 but the script doesn’t seems to work.
Please retry with python2.7 and let me know if it works, thank you 😊

**Comment by 9tin9tin9** [comment]
The reason I used python3 is because python2.7 cannot find pycrypto.
Also, the error seems to be caused by not passing -rsf flag to makerom

**Comment by 9tin9tin9** [comment]
I am now trying to set up the environment in a docket with python2.7 only. See if it works

**Comment by 9tin9tin9** [comment]
<img width="373" alt="Screenshot 2022-08-02 at 10 08 45 AM" src="https://user-images.githubusercontent.com/65890942/182276537-bdc1aaa9-cc11-43af-bcd4-ec3295c7e98f.png">

I have reverted all changes and still not workiing

**Comment by 9tin9tin9** [comment]
I did some more research and installed the correct pip for python2.7 to install pycrypto again.
Now your script works! Thank You!

**Comment by shijimasoft** [comment]
I should update the README with more detailed instructions on how to install PyCrypto. Thanks for opening issue!
