### ISSUE TITLE
which: no decrypt.py in ...

### ISSUE THREAD

**Issue by lrossin** [shijimasoft/cia-unix#6]
Running cia-unix in experimental results in which not being able to find decrypt.py
I worked around this by adding it the directory to $PATH and making it executable.
``export $PATH=$PATH:`pwd` && chmod u+x decrypt.py``

**Comment by shijimasoft** [comment]
Please try to compile the latest source, It should be fixed 😁

**Comment by i30817** [comment]
Pipy no longer allows installs of python2 packages to work in ubuntu 22.04 (or some other incompatibility). So the install of the AES cipher package no longer works, even if you install python2.7 and pip2.

This has to be ported to python 3 'for real'.

**Comment by shijimasoft** [comment]
Hi, `pycryptodome` is a fork of `pycrypto`, and it only works on python3, experimental branch doesn’t rely on pycrypto anymore.
The “Crypto” module is referred to the new library, but it has the same naming.

**Comment by shijimasoft** [comment]
@lrossin did you fixed the error recompiling the latest experimental source?

**Comment by shijimasoft** [comment]
Sorry, I will close this issue

**Comment by shijimasoft** [comment]
91f845c44d474eaf34d2b86e6d0be1b0e5ff81db fixed that
