### ISSUE TITLE
#6 still occurs

### ISSUE THREAD

**Issue by roythearsonist** [shijimasoft/cia-unix#7]
Just complied today from expermential, got this error:

```bash
which: no decrypt.py in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin)
Decrypting: Metroid Prime - Federation Force (CTR-U-BCAE) (v1.2.0) (U).cia...
Unsupported CIA
```

**Comment by shijimasoft** [comment]
Could you try `which decrypt.py` on terminal and post the output? Another thing, which OS are you using?

**Comment by theblobscp** [comment]
I'm using linux, specifically arch. Here's the output:

```bash
which: no decrypt.py in (/usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin)
```

**Comment by shijimasoft** [comment]
Oh, that’s the point, **linux** quit cia-unix since the command `which` send an error return code.

I’ve been testing `cia-unix` only on macos

**Comment by shijimasoft** [comment]
But I’m sure that some old versions (that worked on the same way) works on linux as well 😔

**Comment by theblobscp** [comment]
That sucks. I guess I'll just have to use my 3ds then.

**Comment by shijimasoft** [comment]
91f845c44d474eaf34d2b86e6d0be1b0e5ff81db fixed that
