### ISSUE TITLE
How to use this tool?

### ISSUE THREAD

**Issue by jingzhongchangan** [shijimasoft/cia-unix#9]
Firstly, thanks for the tool!!!

But I met some problems: 
I ran "python decrypt.py  xxx.cia", and got two ncch files, but no cci file, and the two ncch files hadn't been deleted.

This is the screenshot of the folder
<img width="380" alt="image" src="https://user-images.githubusercontent.com/105959405/218666021-9463836d-cc70-434d-9696-a6750f24e033.png">

This is the output on terminal
<img width="622" alt="image" src="https://user-images.githubusercontent.com/105959405/218666121-40415894-2cd7-4ab7-8272-3ab056735346.png">

**Comment by skabber** [comment]
It looks like you called `decrypt.py` manually. This tool is `cia-unix` and uses decrypt.py as just one of its steps. You can either compile the `cia-unix` Crystal file itself. See the README for that or continue with your next manual step and run  `./makerom -f cci -ignoresign -target p -o Dai-Gyakuten-Saiban-decrypted.cia -i Dai-Gyakuten-Saiban2(CN).0.ncch:0:0 -i Dai-Gyakuten-Saiban2(CN).1.ncch:1:1`

**Comment by jingzhongchangan** [comment]
> It looks like you called `decrypt.py` manually. This tool is `cia-unix` and uses decrypt.py as just one of its steps. You can either compile the `cia-unix` Crystal file itself. See the README for that or continue with your next manual step and run `./makerom -f cci -ignoresign -target p -o Dai-Gyakuten-Saiban-decrypted.cia -i Dai-Gyakuten-Saiban2(CN).0.ncch:0:0 -i Dai-Gyakuten-Saiban2(CN).1.ncch:1:1`

Thanks for the reply. 
I figured it out by running cia-unix directly, I got the cci file. And the output in the terminal seemed alright:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/105959405/218673742-5a84aa1c-0210-4b77-a6fa-029dbb380cdd.png">

But when I load the cci file in citra, it said it's not a valid CIA file. And it seemed there's some issues in the cia-unix log: 

<img width="852" alt="image" src="https://user-images.githubusercontent.com/105959405/218673472-d71c1628-df04-4ad9-91a7-50f558a1c808.png">

**Comment by skabber** [comment]
I don't have much experience with CIA files, only .3ds files. I do know that those 2 warnings about failed to sign header are normal and my files work even with those warnings. I'd be happy to take a look further if you can find a way to get me your .cia file.

**Comment by jingzhongchangan** [comment]
> I don't have much experience with CIA files, only .3ds files. I do know that those 2 warnings about failed to sign header are normal and my files work even with those warnings. I'd be happy to take a look further if you can find a way to get me your .cia file.

Much appreciate that!
I'm uploading the cia file onto my google drive, and I'll update here as long as it finished

**Comment by jingzhongchangan** [comment]
> I don't have much experience with CIA files, only .3ds files. I do know that those 2 warnings about failed to sign header are normal and my files work even with those warnings. I'd be happy to take a look further if you can find a way to get me your .cia file.

Hi, skabber, I found another 3ds file and it works fine.
So there's no need to bother you to check it at all.
Thanks again for your kind help and wish you a good day!
